export class CsvFile {
  id: number;
  matricule: number;
  mois: number;
  annee: number;
  type_paie: number;
  codind: number;
  montant_ind: number;
  nature_ind: number;
  grd: number;
  cat: number;
  corps: number;
  codfam: number;
  codsfam: number;
  indice: number;
  nature: number;
  fonc: number;
  dire: number;
  sdir: number;
  serv: number;
  centreg: number;
  gouv: number;
  gouvn: number;
  natorg: number;
  budg: number;
  sitfam: number;
  sexe: number;
  montant_ind_masse_salariale: number;
}
